image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      conda env create -f environment.yml
      conda activate gl4u_rnaseq_2024
    command: |
      jupyter lab --NotebookApp.allow_origin='*' --NotebookApp.ip='0.0.0.0'

ports:
  - port: 8888
    onOpen: open-preview

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true