image:
  file: .gitpod.Dockerfile

tasks:
  - init: echo "Starting GL4U Bootcamp Gitpod"
    command: |
      source $HOME/miniconda3/etc/profile.d/conda.sh
      conda activate gl4u_rnaseq_2024
      jupyter lab --NotebookApp.allow_origin='*' --NotebookApp.ip='0.0.0.0'

ports:
  - port: 8888
    onOpen: open-preview

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true