name: gl4u_rnaseq_2024
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - jupyterlab=4.2.5
  - bash_kernel=0.9.3
  - coreutils=9.5
  - python>3.10
  - star==2.7.11b
  - cutadapt==4.9
  - trim-galore==0.6.10
  - fastqc==0.12.1
  - multiqc==1.24.1
  - rseqc==5.0.3
  - rsem==1.3.3
  - samtools==1.21
  - r-base
  - r-essentials
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-limma
  - notebook
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - ipywidgets
  - pip
  - pip:
    - jupyter_contrib_nbextensions==0.7.0